/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IUniswapV2Router02Interface extends Interface {
    getFunction(nameOrSignature: "WETH" | "addLiquidityETH" | "factory" | "removeLiquidityETH" | "swapExactTokensForETHSupportingFeeOnTransferTokens"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidityETH', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeLiquidityETH', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapExactTokensForETHSupportingFeeOnTransferTokens', values: [BigNumberish, BigNumberish, AddressLike[], AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidityETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidityETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapExactTokensForETHSupportingFeeOnTransferTokens', data: BytesLike): Result;
  }

  

  export interface IUniswapV2Router02 extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUniswapV2Router02;
    waitForDeployment(): Promise<this>;

    interface: IUniswapV2Router02Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addLiquidityETH: TypedContractMethod<
      [token: AddressLike, amountTokenDesired: BigNumberish, amountTokenMin: BigNumberish, amountETHMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountToken: bigint, amountETH: bigint, liquidity: bigint }],
      'payable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeLiquidityETH: TypedContractMethod<
      [token: AddressLike, liquidity: BigNumberish, amountTokenMin: BigNumberish, amountETHMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountToken: bigint, amountETH: bigint }],
      'nonpayable'
    >
    

    
    swapExactTokensForETHSupportingFeeOnTransferTokens: TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidityETH'): TypedContractMethod<
      [token: AddressLike, amountTokenDesired: BigNumberish, amountTokenMin: BigNumberish, amountETHMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint, bigint] & {amountToken: bigint, amountETH: bigint, liquidity: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidityETH'): TypedContractMethod<
      [token: AddressLike, liquidity: BigNumberish, amountTokenMin: BigNumberish, amountETHMin: BigNumberish, to: AddressLike, deadline: BigNumberish, ],
      [[bigint, bigint] & {amountToken: bigint, amountETH: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapExactTokensForETHSupportingFeeOnTransferTokens'): TypedContractMethod<
      [amountIn: BigNumberish, amountOutMin: BigNumberish, path: AddressLike[], to: AddressLike, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }