/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ITreasuryHandler {
      
    export type TreasuryHandlerInfoStruct = {token: AddressLike, liquidityWallet: AddressLike, uniswapV2RouterAddr: AddressLike, uniswapV2FactoryAddr: AddressLike, uniswapV2PairAddr: AddressLike, taxHandlerAddr: AddressLike}

    export type TreasuryHandlerInfoStructOutput = [token: string, liquidityWallet: string, uniswapV2RouterAddr: string, uniswapV2FactoryAddr: string, uniswapV2PairAddr: string, taxHandlerAddr: string] & {token: string, liquidityWallet: string, uniswapV2RouterAddr: string, uniswapV2FactoryAddr: string, uniswapV2PairAddr: string, taxHandlerAddr: string }
  
    }

  export interface TreasuryHandlerInterface extends Interface {
    getFunction(nameOrSignature: "MemeTokenAddress" | "addLiquidity" | "autoAddLiquidity" | "getTreasuryHandlerInfo" | "liquidityWallet" | "owner" | "removeLiquidity" | "renounceOwnership" | "taxHandler" | "token" | "transferOwnership" | "uniswapV2Factory" | "uniswapV2Pair" | "uniswapV2PairAddr" | "uniswapV2Router02" | "uniswapV2Router02Addr"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LiquidityAdded" | "LiquidityRemoved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'MemeTokenAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'addLiquidity', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'autoAddLiquidity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTreasuryHandlerInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidityWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'taxHandler', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uniswapV2Factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'uniswapV2Pair', values?: undefined): string;
encodeFunctionData(functionFragment: 'uniswapV2PairAddr', values?: undefined): string;
encodeFunctionData(functionFragment: 'uniswapV2Router02', values?: undefined): string;
encodeFunctionData(functionFragment: 'uniswapV2Router02Addr', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MemeTokenAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoAddLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreasuryHandlerInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidityWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxHandler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapV2Factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapV2Pair', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapV2PairAddr', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapV2Router02', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapV2Router02Addr', data: BytesLike): Result;
  }

  
    export namespace LiquidityAddedEvent {
      export type InputTuple = [source: AddressLike, sender: AddressLike, to: AddressLike, tokenAmount: BigNumberish, ethAmount: BigNumberish, liquidity: BigNumberish];
      export type OutputTuple = [source: string, sender: string, to: string, tokenAmount: bigint, ethAmount: bigint, liquidity: bigint];
      export interface OutputObject {source: string, sender: string, to: string, tokenAmount: bigint, ethAmount: bigint, liquidity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityRemovedEvent {
      export type InputTuple = [liquidity: BigNumberish, tokenAmount: BigNumberish, ethAmount: BigNumberish];
      export type OutputTuple = [liquidity: bigint, tokenAmount: bigint, ethAmount: bigint];
      export interface OutputObject {liquidity: bigint, tokenAmount: bigint, ethAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TreasuryHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): TreasuryHandler;
    waitForDeployment(): Promise<this>;

    interface: TreasuryHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MemeTokenAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addLiquidity: TypedContractMethod<
      [tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autoAddLiquidity: TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getTreasuryHandlerInfo: TypedContractMethod<
      [],
      [ITreasuryHandler.TreasuryHandlerInfoStructOutput],
      'nonpayable'
    >
    

    
    liquidityWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [liquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    taxHandler: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uniswapV2Factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uniswapV2Pair: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uniswapV2PairAddr: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uniswapV2Router02: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uniswapV2Router02Addr: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MemeTokenAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autoAddLiquidity'): TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTreasuryHandlerInfo'): TypedContractMethod<
      [],
      [ITreasuryHandler.TreasuryHandlerInfoStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'liquidityWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [liquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'taxHandler'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uniswapV2Factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uniswapV2Pair'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uniswapV2PairAddr'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uniswapV2Router02'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uniswapV2Router02Addr'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'LiquidityAdded'): TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
getEvent(key: 'LiquidityRemoved'): TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'LiquidityAdded(address,address,address,uint256,uint256,uint256)': TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
      LiquidityAdded: TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
    

      'LiquidityRemoved(uint256,uint256,uint256)': TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
      LiquidityRemoved: TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }