/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITaxHandler, ITaxHandlerInterface } from "../../interfaces/ITaxHandler.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "taxAmount",
        "type": "uint256"
      }
    ],
    "name": "burnTax",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "getTax",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTaxConfig",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "buyTaxFee",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "sellTaxFee",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "transferTaxFee",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "taxWallet",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "uniswapPair",
            "type": "address"
          }
        ],
        "internalType": "struct ITaxHandler.TaxInfoConfig",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_addr",
        "type": "address"
      }
    ],
    "name": "isTaxFree",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_buyTax",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_sellTax",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_transferTax",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "_taxWallet",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_uniswapPair",
        "type": "address"
      }
    ],
    "name": "setTaxConfig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_addr",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "_isTaxFreeFlag",
        "type": "bool"
      }
    ],
    "name": "setTaxFree",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ITaxHandler__factory {
    static readonly abi = _abi;
    static createInterface(): ITaxHandlerInterface {
      return new Interface(_abi) as ITaxHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITaxHandler {
      return new Contract(address, _abi, runner) as unknown as ITaxHandler;
    }
  }
  