/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITradingRestricHandler, ITradingRestricHandlerInterface } from "../../interfaces/ITradingRestricHandler.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getTradeLimitsInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "maxTxAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxWalletAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dailySellLimit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "dailyTxCountLimit",
            "type": "uint256"
          }
        ],
        "internalType": "struct ITradingRestricHandler.TradeLimit",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_addr",
        "type": "address"
      }
    ],
    "name": "isTradingFree",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_maxTxAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_maxWalletAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_dailySellLimit",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_dailyTxCountLimit",
        "type": "uint256"
      }
    ],
    "name": "setTradeLimits",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_addr",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "_isFree",
        "type": "bool"
      }
    ],
    "name": "setTradingFree",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "uniswapV2Pair",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "balanceOf",
        "type": "uint256"
      }
    ],
    "name": "validateTradeLimits",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ITradingRestricHandler__factory {
    static readonly abi = _abi;
    static createInterface(): ITradingRestricHandlerInterface {
      return new Interface(_abi) as ITradingRestricHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITradingRestricHandler {
      return new Contract(address, _abi, runner) as unknown as ITradingRestricHandler;
    }
  }
  