/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'MyMemeToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyMemeToken__factory>
getContractFactory(name: 'TaxHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TaxHandler__factory>
getContractFactory(name: 'TradingRestricHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TradingRestricHandler__factory>
getContractFactory(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Factory__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Router02__factory>
getContractFactory(name: 'TreasuryHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TreasuryHandler__factory>
getContractFactory(name: 'ITaxHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITaxHandler__factory>
getContractFactory(name: 'ITradingRestricHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITradingRestricHandler__factory>
getContractFactory(name: 'ITreasuryHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITreasuryHandler__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'MyMemeToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyMemeToken>
getContractAt(name: 'TaxHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TaxHandler>
getContractAt(name: 'TradingRestricHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TradingRestricHandler>
getContractAt(name: 'IUniswapV2Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Factory>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'IUniswapV2Router02', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Router02>
getContractAt(name: 'TreasuryHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TreasuryHandler>
getContractAt(name: 'ITaxHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITaxHandler>
getContractAt(name: 'ITradingRestricHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITradingRestricHandler>
getContractAt(name: 'ITreasuryHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITreasuryHandler>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'MyMemeToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyMemeToken>
deployContract(name: 'TaxHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TaxHandler>
deployContract(name: 'TradingRestricHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TradingRestricHandler>
deployContract(name: 'IUniswapV2Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IUniswapV2Router02', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'TreasuryHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TreasuryHandler>
deployContract(name: 'ITaxHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITaxHandler>
deployContract(name: 'ITradingRestricHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITradingRestricHandler>
deployContract(name: 'ITreasuryHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITreasuryHandler>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'MyMemeToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyMemeToken>
deployContract(name: 'TaxHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TaxHandler>
deployContract(name: 'TradingRestricHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TradingRestricHandler>
deployContract(name: 'IUniswapV2Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Factory>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'IUniswapV2Router02', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Router02>
deployContract(name: 'TreasuryHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TreasuryHandler>
deployContract(name: 'ITaxHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITaxHandler>
deployContract(name: 'ITradingRestricHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITradingRestricHandler>
deployContract(name: 'ITreasuryHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITreasuryHandler>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  