/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ITaxHandler {
      
    export type TaxInfoConfigStruct = {buyTaxFee: BigNumberish, sellTaxFee: BigNumberish, transferTaxFee: BigNumberish, taxWallet: AddressLike, uniswapPair: AddressLike}

    export type TaxInfoConfigStructOutput = [buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string] & {buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string }
  
    }

  export interface TaxHandlerInterface extends Interface {
    getFunction(nameOrSignature: "burnTax" | "getTax" | "getTaxConfig" | "isTaxFree" | "owner" | "renounceOwnership" | "setTaxConfig" | "setTaxFree" | "taxWallet" | "transferOwnership" | "uniswapPair"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TaxConfigUpdated" | "TaxDistributed" | "TaxFreeChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'burnTax', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTax', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTaxConfig', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTaxFree', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTaxConfig', values: [BigNumberish, BigNumberish, BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setTaxFree', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'taxWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uniswapPair', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'burnTax', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTax', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTaxConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTaxFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTaxConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTaxFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapPair', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxConfigUpdatedEvent {
      export type InputTuple = [buyTaxFee: BigNumberish, sellTaxFee: BigNumberish, transferTaxFee: BigNumberish, taxWallet: AddressLike, uniswapPair: AddressLike];
      export type OutputTuple = [buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string];
      export interface OutputObject {buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxDistributedEvent {
      export type InputTuple = [amount: BigNumberish, taxWallet: AddressLike];
      export type OutputTuple = [amount: bigint, taxWallet: string];
      export interface OutputObject {amount: bigint, taxWallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxFreeChangedEvent {
      export type InputTuple = [addr: AddressLike, flag: boolean];
      export type OutputTuple = [addr: string, flag: boolean];
      export interface OutputObject {addr: string, flag: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TaxHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): TaxHandler;
    waitForDeployment(): Promise<this>;

    interface: TaxHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    burnTax: TypedContractMethod<
      [taxAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getTax: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTaxConfig: TypedContractMethod<
      [],
      [ITaxHandler.TaxInfoConfigStructOutput],
      'view'
    >
    

    
    isTaxFree: TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTaxConfig: TypedContractMethod<
      [_buyTax: BigNumberish, _sellTax: BigNumberish, _transferTax: BigNumberish, _taxWallet: AddressLike, _uniswapPair: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTaxFree: TypedContractMethod<
      [_addr: AddressLike, _isTaxFreeFlag: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    taxWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uniswapPair: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'burnTax'): TypedContractMethod<
      [taxAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTax'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTaxConfig'): TypedContractMethod<
      [],
      [ITaxHandler.TaxInfoConfigStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isTaxFree'): TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTaxConfig'): TypedContractMethod<
      [_buyTax: BigNumberish, _sellTax: BigNumberish, _transferTax: BigNumberish, _taxWallet: AddressLike, _uniswapPair: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTaxFree'): TypedContractMethod<
      [_addr: AddressLike, _isTaxFreeFlag: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'taxWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uniswapPair'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TaxConfigUpdated'): TypedContractEvent<TaxConfigUpdatedEvent.InputTuple, TaxConfigUpdatedEvent.OutputTuple, TaxConfigUpdatedEvent.OutputObject>;
getEvent(key: 'TaxDistributed'): TypedContractEvent<TaxDistributedEvent.InputTuple, TaxDistributedEvent.OutputTuple, TaxDistributedEvent.OutputObject>;
getEvent(key: 'TaxFreeChanged'): TypedContractEvent<TaxFreeChangedEvent.InputTuple, TaxFreeChangedEvent.OutputTuple, TaxFreeChangedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TaxConfigUpdated(uint256,uint256,uint256,address,address)': TypedContractEvent<TaxConfigUpdatedEvent.InputTuple, TaxConfigUpdatedEvent.OutputTuple, TaxConfigUpdatedEvent.OutputObject>;
      TaxConfigUpdated: TypedContractEvent<TaxConfigUpdatedEvent.InputTuple, TaxConfigUpdatedEvent.OutputTuple, TaxConfigUpdatedEvent.OutputObject>;
    

      'TaxDistributed(uint256,address)': TypedContractEvent<TaxDistributedEvent.InputTuple, TaxDistributedEvent.OutputTuple, TaxDistributedEvent.OutputObject>;
      TaxDistributed: TypedContractEvent<TaxDistributedEvent.InputTuple, TaxDistributedEvent.OutputTuple, TaxDistributedEvent.OutputObject>;
    

      'TaxFreeChanged(address,bool)': TypedContractEvent<TaxFreeChangedEvent.InputTuple, TaxFreeChangedEvent.OutputTuple, TaxFreeChangedEvent.OutputObject>;
      TaxFreeChanged: TypedContractEvent<TaxFreeChangedEvent.InputTuple, TaxFreeChangedEvent.OutputTuple, TaxFreeChangedEvent.OutputObject>;
    
    };
  }