/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ITradingRestricHandler {
      
    export type TradeLimitStruct = {maxTxAmount: BigNumberish, maxWalletAmount: BigNumberish, dailySellLimit: BigNumberish, dailyTxCountLimit: BigNumberish}

    export type TradeLimitStructOutput = [maxTxAmount: bigint, maxWalletAmount: bigint, dailySellLimit: bigint, dailyTxCountLimit: bigint] & {maxTxAmount: bigint, maxWalletAmount: bigint, dailySellLimit: bigint, dailyTxCountLimit: bigint }
  
    }

  export interface TradingRestricHandlerInterface extends Interface {
    getFunction(nameOrSignature: "TradeDataMap" | "getTradeLimitsInfo" | "isTradingFree" | "owner" | "renounceOwnership" | "setTradeLimits" | "setTradingFree" | "transferOwnership" | "validateTradeLimits"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'TradeDataMap', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTradeLimitsInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTradingFree', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTradeLimits', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTradingFree', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'validateTradeLimits', values: [AddressLike, AddressLike, BigNumberish, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'TradeDataMap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTradeLimitsInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTradingFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTradeLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTradingFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateTradeLimits', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TradingRestricHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): TradingRestricHandler;
    waitForDeployment(): Promise<this>;

    interface: TradingRestricHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TradeDataMap: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {lastSellTime: bigint, dailySellAmount: bigint, dailyTxCount: bigint, lastTxTime: bigint }],
      'view'
    >
    

    
    getTradeLimitsInfo: TypedContractMethod<
      [],
      [ITradingRestricHandler.TradeLimitStructOutput],
      'view'
    >
    

    
    isTradingFree: TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTradeLimits: TypedContractMethod<
      [_maxTxAmount: BigNumberish, _maxWalletAmount: BigNumberish, _dailySellLimit: BigNumberish, _dailyTxCountLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTradingFree: TypedContractMethod<
      [_addr: AddressLike, _isFree: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    validateTradeLimits: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, uniswapV2Pair: AddressLike, balanceOf: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TradeDataMap'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {lastSellTime: bigint, dailySellAmount: bigint, dailyTxCount: bigint, lastTxTime: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTradeLimitsInfo'): TypedContractMethod<
      [],
      [ITradingRestricHandler.TradeLimitStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isTradingFree'): TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTradeLimits'): TypedContractMethod<
      [_maxTxAmount: BigNumberish, _maxWalletAmount: BigNumberish, _dailySellLimit: BigNumberish, _dailyTxCountLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTradingFree'): TypedContractMethod<
      [_addr: AddressLike, _isFree: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validateTradeLimits'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, uniswapV2Pair: AddressLike, balanceOf: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }