// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITradingRestricHandler$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITradingRestricHandler";
  readonly sourceName: "contracts/interfaces/ITradingRestricHandler.sol";
  readonly abi: [{"inputs":[],"name":"getTradeLimitsInfo","outputs":[{"components":[{"internalType":"uint256","name":"maxTxAmount","type":"uint256"},{"internalType":"uint256","name":"maxWalletAmount","type":"uint256"},{"internalType":"uint256","name":"dailySellLimit","type":"uint256"},{"internalType":"uint256","name":"dailyTxCountLimit","type":"uint256"}],"internalType":"struct ITradingRestricHandler.TradeLimit","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_addr","type":"address"}],"name":"isTradingFree","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_maxTxAmount","type":"uint256"},{"internalType":"uint256","name":"_maxWalletAmount","type":"uint256"},{"internalType":"uint256","name":"_dailySellLimit","type":"uint256"},{"internalType":"uint256","name":"_dailyTxCountLimit","type":"uint256"}],"name":"setTradeLimits","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_addr","type":"address"},{"internalType":"bool","name":"_isFree","type":"bool"}],"name":"setTradingFree","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"uniswapV2Pair","type":"address"},{"internalType":"uint256","name":"balanceOf","type":"uint256"}],"name":"validateTradeLimits","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITradingRestricHandler.sol";
  readonly buildInfoId: "solc-0_8_28-51a572951e7623a3b6c91997a4e4fba0de2bf366";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITradingRestricHandler"]: ITradingRestricHandler$Type;
    ["contracts/interfaces/ITradingRestricHandler.sol:ITradingRestricHandler"]: ITradingRestricHandler$Type;
  }
}