// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockUniswapV2Pair$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockUniswapV2Pair";
  readonly sourceName: "contracts/mock/MockUniswapV2Pair.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"spender","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"owner","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5061017b8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063095ea7b31461004357806323b872dd1461006e57806370a0823114610085575b5f5ffd5b6100596100513660046100c3565b600192915050565b60405190151581526020015b60405180910390f35b61005961007c3660046100eb565b60019392505050565b61009a610093366004610125565b506103e890565b604051908152602001610065565b80356001600160a01b03811681146100be575f5ffd5b919050565b5f5f604083850312156100d4575f5ffd5b6100dd836100a8565b946020939093013593505050565b5f5f5f606084860312156100fd575f5ffd5b610106846100a8565b9250610114602085016100a8565b929592945050506040919091013590565b5f60208284031215610135575f5ffd5b61013e826100a8565b939250505056fea2646970667358221220c2c55879b0a59d3b0ff2c505ac90cbe292e786faa77a4d41e1e4ad5f83739e6b64736f6c634300081c0033";
  readonly deployedBytecode: "0x608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063095ea7b31461004357806323b872dd1461006e57806370a0823114610085575b5f5ffd5b6100596100513660046100c3565b600192915050565b60405190151581526020015b60405180910390f35b61005961007c3660046100eb565b60019392505050565b61009a610093366004610125565b506103e890565b604051908152602001610065565b80356001600160a01b03811681146100be575f5ffd5b919050565b5f5f604083850312156100d4575f5ffd5b6100dd836100a8565b946020939093013593505050565b5f5f5f606084860312156100fd575f5ffd5b610106846100a8565b9250610114602085016100a8565b929592945050506040919091013590565b5f60208284031215610135575f5ffd5b61013e826100a8565b939250505056fea2646970667358221220c2c55879b0a59d3b0ff2c505ac90cbe292e786faa77a4d41e1e4ad5f83739e6b64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mock/MockUniswapV2Pair.sol";
  readonly buildInfoId: "solc-0_8_28-bc2b1079036e000f4ad2b119b21babfa256064cf";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockUniswapV2Pair"]: MockUniswapV2Pair$Type;
    ["contracts/mock/MockUniswapV2Pair.sol:MockUniswapV2Pair"]: MockUniswapV2Pair$Type;
  }
}