// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockWETH$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockWETH";
  readonly sourceName: "contracts/mock/MockWETH.sol";
  readonly abi: [{"inputs":[],"name":"deposit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50609080601a5f395ff3fe6080604052600436106025575f3560e01c80632e1a7d4d146029578063d0e30db0146042575b5f5ffd5b3480156033575f5ffd5b506042603f3660046044565b50565b005b5f602082840312156053575f5ffd5b503591905056fea26469706673582212208ffcf44fd27ac884c2af081379519ac00a939f17892ecc3b5b66b1547a9da4f164736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052600436106025575f3560e01c80632e1a7d4d146029578063d0e30db0146042575b5f5ffd5b3480156033575f5ffd5b506042603f3660046044565b50565b005b5f602082840312156053575f5ffd5b503591905056fea26469706673582212208ffcf44fd27ac884c2af081379519ac00a939f17892ecc3b5b66b1547a9da4f164736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mock/MockWETH.sol";
  readonly buildInfoId: "solc-0_8_28-bc2b1079036e000f4ad2b119b21babfa256064cf";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockWETH"]: MockWETH$Type;
    ["contracts/mock/MockWETH.sol:MockWETH"]: MockWETH$Type;
  }
}