/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ITaxHandler {
      
    export type TaxInfoConfigStruct = {buyTaxFee: BigNumberish, sellTaxFee: BigNumberish, transferTaxFee: BigNumberish, taxWallet: AddressLike, uniswapPair: AddressLike}

    export type TaxInfoConfigStructOutput = [buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string] & {buyTaxFee: bigint, sellTaxFee: bigint, transferTaxFee: bigint, taxWallet: string, uniswapPair: string }
  
    }

  export interface ITaxHandlerInterface extends Interface {
    getFunction(nameOrSignature: "burnTax" | "getTax" | "getTaxConfig" | "isTaxFree" | "setTaxConfig" | "setTaxFree"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'burnTax', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTax', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTaxConfig', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTaxFree', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTaxConfig', values: [BigNumberish, BigNumberish, BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setTaxFree', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'burnTax', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTax', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTaxConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTaxFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTaxConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTaxFree', data: BytesLike): Result;
  }

  

  export interface ITaxHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITaxHandler;
    waitForDeployment(): Promise<this>;

    interface: ITaxHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    burnTax: TypedContractMethod<
      [taxAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getTax: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getTaxConfig: TypedContractMethod<
      [],
      [ITaxHandler.TaxInfoConfigStructOutput],
      'view'
    >
    

    
    isTaxFree: TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setTaxConfig: TypedContractMethod<
      [_buyTax: BigNumberish, _sellTax: BigNumberish, _transferTax: BigNumberish, _taxWallet: AddressLike, _uniswapPair: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTaxFree: TypedContractMethod<
      [_addr: AddressLike, _isTaxFreeFlag: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'burnTax'): TypedContractMethod<
      [taxAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTax'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTaxConfig'): TypedContractMethod<
      [],
      [ITaxHandler.TaxInfoConfigStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isTaxFree'): TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setTaxConfig'): TypedContractMethod<
      [_buyTax: BigNumberish, _sellTax: BigNumberish, _transferTax: BigNumberish, _taxWallet: AddressLike, _uniswapPair: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTaxFree'): TypedContractMethod<
      [_addr: AddressLike, _isTaxFreeFlag: boolean, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }