/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ITradingRestricHandler {
      
    export type TradeLimitStruct = {maxTxAmount: BigNumberish, maxWalletAmount: BigNumberish, dailySellLimit: BigNumberish, dailyTxCountLimit: BigNumberish}

    export type TradeLimitStructOutput = [maxTxAmount: bigint, maxWalletAmount: bigint, dailySellLimit: bigint, dailyTxCountLimit: bigint] & {maxTxAmount: bigint, maxWalletAmount: bigint, dailySellLimit: bigint, dailyTxCountLimit: bigint }
  
    }

  export interface ITradingRestricHandlerInterface extends Interface {
    getFunction(nameOrSignature: "getTradeLimitsInfo" | "isTradingFree" | "setTradeLimits" | "setTradingFree" | "validateTradeLimits"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getTradeLimitsInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTradingFree', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTradeLimits', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTradingFree', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'validateTradeLimits', values: [AddressLike, AddressLike, BigNumberish, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getTradeLimitsInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTradingFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTradeLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTradingFree', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateTradeLimits', data: BytesLike): Result;
  }

  

  export interface ITradingRestricHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITradingRestricHandler;
    waitForDeployment(): Promise<this>;

    interface: ITradingRestricHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getTradeLimitsInfo: TypedContractMethod<
      [],
      [ITradingRestricHandler.TradeLimitStructOutput],
      'view'
    >
    

    
    isTradingFree: TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setTradeLimits: TypedContractMethod<
      [_maxTxAmount: BigNumberish, _maxWalletAmount: BigNumberish, _dailySellLimit: BigNumberish, _dailyTxCountLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTradingFree: TypedContractMethod<
      [_addr: AddressLike, _isFree: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    validateTradeLimits: TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, uniswapV2Pair: AddressLike, balanceOf: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getTradeLimitsInfo'): TypedContractMethod<
      [],
      [ITradingRestricHandler.TradeLimitStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isTradingFree'): TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setTradeLimits'): TypedContractMethod<
      [_maxTxAmount: BigNumberish, _maxWalletAmount: BigNumberish, _dailySellLimit: BigNumberish, _dailyTxCountLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTradingFree'): TypedContractMethod<
      [_addr: AddressLike, _isFree: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validateTradeLimits'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, amount: BigNumberish, uniswapV2Pair: AddressLike, balanceOf: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }