/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ITreasuryHandler {
      
    export type TreasuryHandlerInfoStruct = {token: AddressLike, liquidityWallet: AddressLike, uniswapV2RouterAddr: AddressLike, uniswapV2FactoryAddr: AddressLike, uniswapV2PairAddr: AddressLike, taxHandlerAddr: AddressLike}

    export type TreasuryHandlerInfoStructOutput = [token: string, liquidityWallet: string, uniswapV2RouterAddr: string, uniswapV2FactoryAddr: string, uniswapV2PairAddr: string, taxHandlerAddr: string] & {token: string, liquidityWallet: string, uniswapV2RouterAddr: string, uniswapV2FactoryAddr: string, uniswapV2PairAddr: string, taxHandlerAddr: string }
  
    }

  export interface ITreasuryHandlerInterface extends Interface {
    getFunction(nameOrSignature: "addLiquidity" | "autoAddLiquidity" | "getTreasuryHandlerInfo" | "removeLiquidity"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LiquidityAdded" | "LiquidityRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'addLiquidity', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'autoAddLiquidity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTreasuryHandlerInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeLiquidity', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoAddLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreasuryHandlerInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeLiquidity', data: BytesLike): Result;
  }

  
    export namespace LiquidityAddedEvent {
      export type InputTuple = [source: AddressLike, sender: AddressLike, to: AddressLike, tokenAmount: BigNumberish, ethAmount: BigNumberish, liquidity: BigNumberish];
      export type OutputTuple = [source: string, sender: string, to: string, tokenAmount: bigint, ethAmount: bigint, liquidity: bigint];
      export interface OutputObject {source: string, sender: string, to: string, tokenAmount: bigint, ethAmount: bigint, liquidity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityRemovedEvent {
      export type InputTuple = [liquidity: BigNumberish, tokenAmount: BigNumberish, ethAmount: BigNumberish];
      export type OutputTuple = [liquidity: bigint, tokenAmount: bigint, ethAmount: bigint];
      export interface OutputObject {liquidity: bigint, tokenAmount: bigint, ethAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ITreasuryHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITreasuryHandler;
    waitForDeployment(): Promise<this>;

    interface: ITreasuryHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addLiquidity: TypedContractMethod<
      [tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autoAddLiquidity: TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getTreasuryHandlerInfo: TypedContractMethod<
      [],
      [ITreasuryHandler.TreasuryHandlerInfoStructOutput],
      'nonpayable'
    >
    

    
    removeLiquidity: TypedContractMethod<
      [liquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addLiquidity'): TypedContractMethod<
      [tokenAmount: BigNumberish, ethAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autoAddLiquidity'): TypedContractMethod<
      [tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTreasuryHandlerInfo'): TypedContractMethod<
      [],
      [ITreasuryHandler.TreasuryHandlerInfoStructOutput],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeLiquidity'): TypedContractMethod<
      [liquidity: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LiquidityAdded'): TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
getEvent(key: 'LiquidityRemoved'): TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;

    filters: {
      
      'LiquidityAdded(address,address,address,uint256,uint256,uint256)': TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
      LiquidityAdded: TypedContractEvent<LiquidityAddedEvent.InputTuple, LiquidityAddedEvent.OutputTuple, LiquidityAddedEvent.OutputObject>;
    

      'LiquidityRemoved(uint256,uint256,uint256)': TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
      LiquidityRemoved: TypedContractEvent<LiquidityRemovedEvent.InputTuple, LiquidityRemovedEvent.OutputTuple, LiquidityRemovedEvent.OutputObject>;
    
    };
  }